# Generated by Django 4.2.5 on 2024-11-09 22:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('age', models.PositiveSmallIntegerField(default=0, verbose_name='Вік')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='actors/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Автори',
                'verbose_name_plural': 'автори',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категорія')),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Назва')),
                ('tagline', models.CharField(default='', max_length=100, verbose_name='Гасло')),
                ('description', models.TextField(verbose_name='Опис')),
                ('poster', models.ImageField(upload_to='events/', verbose_name='Постер')),
                ('year', models.PositiveSmallIntegerField(default=2023, verbose_name='Дата виходу')),
                ('country', models.CharField(max_length=255, verbose_name='Країна')),
                ('world_premiere', models.DateField(default=datetime.date.today, verbose_name="Прем'єра в світі")),
                ('budget', models.PositiveIntegerField(default=0, help_text='in $', verbose_name='Ціна')),
                ('fees_in_USA', models.PositiveIntegerField(default=0, help_text='in $', verbose_name='Збори в США')),
                ('fees_in_world', models.PositiveIntegerField(default=0, help_text='in $', verbose_name='Збори в світі')),
                ('url', models.SlugField(max_length=255, unique=True)),
                ('draft', models.BooleanField(default=False, verbose_name='Чорновик')),
                ('actors', models.ManyToManyField(related_name='film_actor', to='events.avtor', verbose_name='Співавтор')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.category', verbose_name='Категорія')),
                ('directors', models.ManyToManyField(related_name='film_director', to='events.avtor', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Івент',
                'verbose_name_plural': 'Івенти',
            },
        ),
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значення')),
            ],
            options={
                'verbose_name': 'Зірка рейтингу',
                'verbose_name_plural': 'Зірки рейтингу',
                'ordering': ['-value'],
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('description', models.TextField(verbose_name='Опис')),
                ('url', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Підкатегорія',
                'verbose_name_plural': 'Підкатегорії',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255, verbose_name="Ім'я")),
                ('text', models.TextField(max_length=5000, verbose_name='Коментар')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='івент')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.reviews', verbose_name='Батько')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255, verbose_name='ІР адреса')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='івент')),
                ('star', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.ratingstar', verbose_name='зірка')),
            ],
            options={
                'verbose_name': 'Рейтинг',
                'verbose_name_plural': 'Рейтинги',
            },
        ),
        migrations.CreateModel(
            name='EventShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Опис')),
                ('image', models.ImageField(upload_to='event_shots/', verbose_name='Зображення')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Івент')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='genres',
            field=models.ManyToManyField(to='events.subcategory', verbose_name='жанри'),
        ),
    ]
