# Generated by Django 4.2.5 on 2024-11-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='actors',
        ),
        migrations.AddField(
            model_name='event',
            name='avtors',
            field=models.ManyToManyField(related_name='film_avtor', to='events.avtor', verbose_name='Співавтор'),
        ),
        migrations.AlterField(
            model_name='avtor',
            name='image',
            field=models.ImageField(upload_to='avtors/', verbose_name='Фото'),
        ),
    ]
